services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myblog
    container_name: myblog
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9060:80"
    networks:
      - laravel


  mysql:
    image: mysql:5.7
    container_name: mysql_blog
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_blog
      MYSQL_ROOT_PASSWORD: root  # Set the root password
    ports:
      - "3309:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - laravel

  # PHPMYADMIN SERVER
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_blog
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8088:80
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql:
